version: '3.8'

services:
  spring-boot-app:
    image: carrefour-delivery-kata
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgresql
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/<database-name> # Replace <database-name> with your PostgreSQL database name
      SPRING_DATASOURCE_USERNAME: <username>
      SPRING_DATASOURCE_PASSWORD: <password>
    networks:
      - backend

  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_DB: <database-name>
      POSTGRES_USER: <username>
      POSTGRES_PASSWORD: <password>
    ports:
      - "5432:5432"
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge
