server:
  port: 8080

spring:
  redis:
    host: localhost
    port: 6379
  batch:
    initialize-schema: always
    job:
      enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://host:port/dbName
    username: username
    password: password

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
  flyway:
    baseline-on-migrate: true
    check-location: true
    enabled: true
    locations: classpath:db/migration/all,classpath:db/data
    out-of-order: true
    validate-on-migrate: true




